version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8    
    commands:
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - npm install uuid
    - serverless deploy --stage $stage
