service: copyfilesfromsources3todestS3
provider:
  name: aws
  runtime: python3.7

# you can overwrite defaults here
  stage: ${opt:stage, 'qa'}
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"
# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#  exclude:
#    - README.md
#    - buildspec.yml
#    - env.yml

functions:
  hello:
    handler: handler.hello
    package:
      exclude: 
        - "*/**"
      include:
        - handler.py
    environment:
      desti: dest11-${self:provider.stage}
      source: source11-${self:provider.stage}
  eventTrigger:
    handler: handler1.eventTrigger
    package:
      exclude: 
        - "*/**"
      include:
        - handler1.py
    events:
     - s3:
        bucket: dest11-${self:provider.stage}
        event: s3:ObjectCreated:*
        existing: true

    

