service: copyfilesfromsources3todestS3
provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'qa'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
package:
  individually: true
  exclude:
    - ./**
functions:
  hello:
    handler: handler.hello
    package:
      include:
        - handler.py
    environment:
      desti: dest11-${self:provider.stage}
      source: source11-${self:provider.stage}
  eventTrigger:
    handler: handler1.eventTrigger
    package:
      include:
        - handler1.py
    events:
     - s3:
        bucket: dest11-${self:provider.stage}
        event: s3:ObjectCreated:*
        existing: true

    

